version: 2.1

jobs:
  test-app:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Execute tests
          command: mvn verify

workflows:
  test-app:
    jobs:
      - test-app
