version: 2.1

executors:
  ubuntu-16-04:
    machine:
      image: ubuntu-1604:201903-01
      docker_layer_caching: true

jobs:
  build:
    executor: ubuntu-16-04
    steps:
      - run:
          name: dependencies-downloading
          command: mvn clean install -Dmaven.test.skip=true

      - persist_to_workspace:
          root: .
          paths: target/*

      - run:
          name: "Say hello"
          command: "Estoy probando ahora esto"

workflows:
  say-hello-workflow:
    jobs:
      - build